# Generated by Django 4.1.2 on 2024-07-05 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(db_column='id_comuna', primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('id_tipo_ser', models.AutoField(db_column='id_tipo_ser', primary_key=True, serialize=False)),
                ('Servicio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(max_length=14)),
                ('Detalles_servicio', models.CharField(max_length=150)),
                ('comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.CASCADE, to='RayoMakuin.comuna')),
                ('tipo_ser', models.ForeignKey(db_column='id_tipo_ser', on_delete=django.db.models.deletion.CASCADE, to='RayoMakuin.tipo_servicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
