# Generated by Django 4.1.2 on 2024-07-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RayoMakuin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='trabajoListo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
