# Generated by Django 4.1.2 on 2024-07-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RayoMakuin', '0002_formulario_trabajolisto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='Detalles_servicio',
            field=models.TextField(max_length=150),
        ),
    ]
