# Generated by Django 4.1.2 on 2024-06-17 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('id_tipo_ser', models.AutoField(db_column='id_tipo_ser', primary_key=True, serialize=False)),
                ('Servicio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=45)),
                ('comuna', models.CharField(max_length=20)),
                ('Detalles_servicio', models.CharField(max_length=20)),
                ('Ingrese_archivo', models.CharField(max_length=20)),
                ('id_tipo_ser', models.ForeignKey(db_column='id_tipo_ser', on_delete=django.db.models.deletion.CASCADE, to='RayoMakuin.tipo_servicio')),
            ],
        ),
    ]
